// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZfa5Dm_BdJemEPdo6l-_NQ_iHyA7U2Ss',
    appId: '1:377839320538:web:2e459eed5c7c3e95ffd4e3',
    messagingSenderId: '377839320538',
    projectId: 'goolu-fddd7',
    authDomain: 'goolu-fddd7.firebaseapp.com',
    storageBucket: 'goolu-fddd7.appspot.com',
    measurementId: 'G-YJRZ9GBH7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKnRM5-Zx5l6x3JJKivqaSApRXFkbcJc',
    appId: '1:377839320538:android:d65e7bacf1c3403dffd4e3',
    messagingSenderId: '377839320538',
    projectId: 'goolu-fddd7',
    storageBucket: 'goolu-fddd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYtTEyK420WIhJ9axSO32X4zppUCjgxBY',
    appId: '1:377839320538:ios:6300660b036b329effd4e3',
    messagingSenderId: '377839320538',
    projectId: 'goolu-fddd7',
    storageBucket: 'goolu-fddd7.appspot.com',
    iosBundleId: 'com.example.goolu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYtTEyK420WIhJ9axSO32X4zppUCjgxBY',
    appId: '1:377839320538:ios:6300660b036b329effd4e3',
    messagingSenderId: '377839320538',
    projectId: 'goolu-fddd7',
    storageBucket: 'goolu-fddd7.appspot.com',
    iosBundleId: 'com.example.goolu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZfa5Dm_BdJemEPdo6l-_NQ_iHyA7U2Ss',
    appId: '1:377839320538:web:e245ebffbe9fc726ffd4e3',
    messagingSenderId: '377839320538',
    projectId: 'goolu-fddd7',
    authDomain: 'goolu-fddd7.firebaseapp.com',
    storageBucket: 'goolu-fddd7.appspot.com',
    measurementId: 'G-04QR7HG8YK',
  );

}